### ISSUE TITLE
Compilation Issue 

### ISSUE THREAD

**Issue by amannayak0007** [txaiwieser/FityIt#1]
SKUtils Folder Is missing. :(

**Comment by amannayak0007** [comment]
Can u please fix this?

**Comment by txaiwieser** [comment]
Going to fix it as soon as possible. I'm having a busy week at work, so haven't had the time yet.

**Comment by amannayak0007** [comment]
It's almost 15 days we last talked I know ur having a busy time. I'm Still waiting for your repository to update. I want to learn Button Animation & Transition Which u Implemented In this game that's why I'm asking. Thanks.

**Comment by txaiwieser** [comment]
Hey Aman, I had some time to fix it on the weekend, should be working now. 

I also went to 2016 WWDC with scholarship :)
